### PR TITLE
AfuTUB exam circuitikz

### PR DESCRIPTION
**Pull request by dm4go**
The circuitikz version of the ham radio exam questions from the [AfuTUB repository](https://git.dk0tu.de/afutub/kurs/-/tree/42-ressourcen-und-quellenstruktur-vereinheitlichen/Ressourcen/Abbildungen).
Newly added: 

- TC106
- TC704
- TC705
- TC706
- TC707
- TD207
- TD306
- TD319
- TD401
- TD501
- TD502
- TD505
- TD506
- TD507
- TD508
- TD511
- TD513
- TD514
- TF311
- TF314
- TG212
- TJ601

### CODE REVIEW

**Comment by myzinsky** [comment]
First of all, thank you very much for your contribution!

I have some change requests here, mainly because I think that BNetzA will like it more if we are 95% consistent with the originals:

- TC106: This is a class E question. Please add a E_ in front of the file name. So far we don't have pictures for class E, I will rename the class A pictures to A_* later on. Furthermore, we need for each answer a separate picture. Please also follow the naming that we used there.
- TC704: Please use San-Serif fonts. This should be fixed by using this code 
```TeX
\usepackage{amsmath}
\usepackage{unicode-math}
\setmathfont{Fira Math}
\setmathfont[range=up]{Roboto}
\setmathfont[range=it]{Roboto-Italic}
\setmathfont[range=\int]{Fira Math}
\usepackage[euler]{textgreek}
```
- TC705: OK
- TC706: OK
- TC707:  use Sans-Serif.
- TD207: use Sans-Serif.
- TD306: Use Sans-Serif fonts. Second C should be an elco as in the original image!
- TD319: Use Sans-Serif fonts. Second C should be an elco as in the original image! The question mark is missing in the upper right corner. The original does not include 7806, this should be removed.
- TD401: OK
- TD501: The elco has a plus with circle. It should be without circle such that it is constant with your other pictures.
- TD502: The elco has a plus with circle. It should be without circle such that it is constant with your other pictures.
- TD505: OK
- TD506: Use Serif fonts. The arrow heads of the vari-caps should be a T form.
- TD507: Spacing of NF and ZF to the line should be increased. The bubble in the transformator is missing.
- TD508: ZF should be placed more right. The plus of the elco is again with circle. The arrow heads of the various-caps should be a T form.
- TD511: Placement of text should be similar to the original. At least with a bit more distance to the lines. The bubble at the transformator is missing. The plus should be without circle. The placement of the ground could be a bit lower.
- TD513: Use Sans-Serif fonts. The arrow heads should have a T shape. The C_5 label overlaps with the transformator. Please change this (e.g. by making more space)
- TD514: Use the same symbol for the diode and make some space for the transistor: 
image

- TF311: Use Serif fonts, adjust arrow heads from Cs.
- TF314: Use Serif fonts, adjust arrow heads from Cs.
- TG212: Use the same symbol for the diode
- TJ601: Would be nice to have the straight 45 degree arrow heads instead of the curvy ones.


It would be nice if you could do these changes. If not possible just let me know, then I will accept the PR and do these changes later on... But of course I prefer if you could do it. 

Thank you very much!!

**Comment by dm4go** [comment]
Thanks for the feedback, i will try to get to implement your feedback as soon as possible.

**Comment by dm4go** [comment]
I extended the makefile by a function to allow for compilation of a single question
- [x] TC106
- [x] TC704
- [x] TC207
- [x] TC306
- [x]  TD319 in the [DARC-Course](https://www.darc.de/fileadmin/filemounts/referate/ajw/Onlinelehrgang/a17/TD319.gif) includes the 7806
- [x] TD501
- [x] TD502
- [x] TD506: Currently searching for a better solution for making trimmer capacitors instead of making them manually
- [x] TD507
- [x] TD508
- [x] TD511
- [x] TD513
- [x] TD514
- [x] TF311
- [x] TF314
- [x] TG212
- [x] TJ601

**Comment by myzinsky** [comment]
Some small remarks:

- E_TC106*: needs Sans-Serif
- TC704: X and Y should not be italic. Just don't use Math mode.
- TD207: The Cs should not be italic $\mbox{C}_1$ would be a valid solution.
- TD306: Try to avoid italics. Also if possible place captions of T1 and T2 outside of the circle. Would look cleaner.
- TD319: OK
- TD501: OK
- TD502: OK

**Comment by myzinsky** [comment]
- TC106: is still serif... I have no idea why?
- TC704: OK
- TD207: OK
- TD306: OK
- TD319: OK
- TD501: OK
- TD502: OK
- TD506: f_1 and f_2 are italic. Shouldn't be italic.
- TD507: OK
- TD508: OK
- TD512: OK

Seams that the new Circuit Tikz causes some changes in other questions...

image

But we can fix them later.

**Comment by dm4go** [comment]
Hmm weird. I included the new circuitikz because it included the change to the arrows for variable components which will be included in the next release but without an update would require making a custom component (Many thanks to Romano Giannetti from circuitikz for pushing the update not a day after my request). I will try to look into TC106 but I need to figure out why tex files with sans serif don't compile on my end even though i installed all dependencies (i currently test those change on overleaf which is a roundabout way).

**Comment by dm4go** [comment]
TF314 the Arrowhead from C1 is according to the Exam Questions.
The fix for the arrow tips is now in the newest release of circuitikz (v.1.3.3) but the usage is different.
I would replace all instances of "bipoles/tunable arrow={Bar}" with the in the manual specified "tunable start arrow={Bar}" if the repository updates to the version 1.3.3 of circuitikz.

**Comment by myzinsky** [comment]
Hi @dm4go I will look on your latest changes soon. We have to change the license to https://www.govdata.de/dl-de/zero-2-0 would that be still fine for you?

**Comment by dm4go** [comment]
That is fine by me

**Comment by myzinsky** [comment]
Please add also in a future commit your name and callsign to the readme, such that we can acknowledge your help there ;-)

**Pull request merged**
